services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
    ports:
      - "5432:5432"

  auth_service:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:

volumes:
  pgdata: